name: build

# This workflow runs if the CI workflow is successful
on:
  workflow_run:
    workflows: ["CI"] # Keep consistent with actual CI workflow name
    types: 
      - completed
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Install
        run: make install

      - name: Clean up
        run: make clean
