name: build

# This workflow runs if the CI workflow is successful
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      # Syncs dependencies and builds the project
      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Clean up
        run: make clean
